### ISSUE TITLE
onEndReached wont trigger after refreshControl

### ISSUE THREAD

**Issue by jjdp** [phil-r/react-native-grid-component#6]
this sometimes happen. even with your example

**Comment by phil-r** [comment]
Hello @jjdp,
`refreshControl` was just recently added, I haven't tested it much, I will try to take a look this week. 

P.S. PRs are alway welcome ;)

**Comment by chongxx** [comment]
This problem is in file `index.js` line 15 and 102,  `onEndReachedThreshold` value is screen height, so this happens.Modify `onEndReachedThreshold`!  [doc](http://facebook.github.io/react-native/releases/0.37/docs/listview.html#onendreachedthreshold). 
English is not my native language; please excuse typing errors.

**Comment by jjdp** [comment]
i see.

but specifically, another use case is that when you refresh twice (swipe down) even with an interval of a second. onEndReached wont trigger

**Comment by phil-r** [comment]
Closing this, as I never encountered this
